version: '3.8'

services:

  account:
    image: deepagangadhar/account-service:v1
    ports:
      - "3000:3000"
    networks:
      - bank-net
    deploy:
      replicas: 2

  transaction:
    image: deepagangadhar/transaction-service:v1
    ports:
      - "4000:4000"
    networks:
      - bank-net
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s

  notification:
    image: deepagangadhar/notification-service:v1
    networks:
      - bank-net
    deploy:
      replicas: 2
      restart_policy:
        condition: any

networks:
  bank-net:
    driver: overlay
