version: '3.8'

services:

  account:
    image: deepagangadhar/account-service:v1
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    networks:
      - bank-net
    deploy:
      replicas: 2

  transaction:
    image: deepagangadhar/transaction-service:v2
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: ingress
    networks:
      - bank-net
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s

  notification:
    image: deepagangadhar/notification-service:v1
    networks:
      - bank-net
    deploy:
      replicas: 2
      restart_policy:
        condition: any

networks:
  bank-net:
    driver: overlay
